
prettyp_comp_writers.pdf: prettyp_comp_writers.tex
	texi2pdf prettyp_comp_writers.tex

latex: 
	latex prettyp_comp_writers
	bibtex prettyp_comp_writers
	latex prettyp_comp_writers
	latex prettyp_comp_writers
